services:
  frontend:
    image: js_app_frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://projectsigmatrading.ru/api
    command: npm start
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend/logs:/app/logs
    environment:
      - LOG_PATH=/app/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
    restart: unless-stopped

  backend:
    image: python_app_backend
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      MODE_WORK: server
      ADMIN_KEY: ${ADMIN_KEY}
    build:
      context: ./backend
    command: sh -c "cd src && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"
    networks:
      - app-network
    depends_on:
      - dataBase
    volumes:
      - ./backend/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
    restart: unless-stopped

  celery_beat:
    image: python_app_ml_pipeline_celery_beat
    build:
      context: ./MLPipeline
      dockerfile: Dockerfile.beat
    command: sh -c "cd src && celery -A celery_beat beat --loglevel=info"
    networks:
      - app-network
    depends_on:
      - redis
      - dataBase
      - celery_worker
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      GLOBAL_WORK_MODE: 'imitation'
    volumes:
      - ./MLPipeline/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped

  celery_worker:
    image: python_app_ml_pipeline_celery_worker
    build:
      context: ./MLPipeline
      dockerfile: Dockerfile.worker
    command: >
      sh -c "cd src && celery -A celery_worker worker 
      -Q high_priority,medium_priority,low_priority,default
      --loglevel=info 
      --concurrency=3 
      --max-tasks-per-child=40 
      --prefetch-multiplier=1"
    networks:
      - app-network
    depends_on:
      - dataBase
      - redis
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      GLOBAL_WORK_MODE: 'imitation'
    volumes:
      - ./MLPipeline/src/config:/app/src/config
      - ./MLPipeline/src/output:/app/src/output
      - ./MLPipeline/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1768M
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped

  dataBase:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 384M
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped

  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_SERVER_ROOT_URL=https://projectsigmatrading.ru/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    depends_on:
      - loki
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    restart: unless-stopped

volumes:
  db-data:
    name: projectsigmatrading_db-data
    driver: local
  loki_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
