services:
  frontend:
    image: js_app_frontend
    build: 
      context: ./frontend
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  backend:
    image: python_app_backend
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    build:
      context: ./backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - dataBase
      - redis
    volumes:
      - ./backend/logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  celery_beat:
    image: python_app_ml_pipeline_celery_beat
    build: ./MLPipeline
    command: celery -A tasks beat --loglevel=info
    networks:
      - app-network
    depends_on:
      - redis
      - dataBase
      - celery_worker
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./MLPipeline/logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 128M
    restart: unless-stopped

  celery_worker:
    image: python_app_ml_pipeline_celery_worker
    build: ./MLPipeline
    command: celery -A tasks worker --loglevel=info --concurrency=1 --max-tasks-per-child=50
    networks:
      - app-network
    depends_on:
      - dataBase
      - redis
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./MLPipeline/logs:/app/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 128M
    restart: unless-stopped

  dataBase:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - dsmlai_edu_db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2048M
    restart: unless-stopped

volumes:
  dsmlai_edu_db-data:
    external: true

networks:
  app-network:
    driver: bridge
