services:
  frontend:
    image: js_app_frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://projectsigmatrading.ru/api
    command: npm start
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend/logs:/app/logs
    environment:
      - LOG_PATH=/app/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
    restart: unless-stopped
    profiles: ["dev"]

  backend:
    image: python_app_backend
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      MODE_WORK: server
      ADMIN_KEY: ${ADMIN_KEY}
    build:
      context: ./backend
    command: sh -c "cd src && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"
    networks:
      - app-network
    depends_on:
      - dataBase
    volumes:
      - ./backend/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
    restart: unless-stopped
    profiles: ["dev"]

  celery_beat:
    image: python_app_ml_pipeline_celery_beat
    build:
      context: ./MLPipeline
      dockerfile: Dockerfile.beat
    command: sh -c "cd src && celery -A celery_beat beat --loglevel=info"
    networks:
      - app-network
    depends_on:
      - redis
      - dataBase
      - celery_worker
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      GLOBAL_WORK_MODE: 'imitation'
    volumes:
      - ./MLPipeline/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped
    profiles: ["dev"]

  celery_worker:
    image: python_app_ml_pipeline_celery_worker
    build:
      context: ./MLPipeline
      dockerfile: Dockerfile.worker
    command: >
      sh -c "cd src && celery -A celery_worker worker 
      -Q high_priority,medium_priority,low_priority,default
      --loglevel=info 
      --concurrency=3 
      --max-tasks-per-child=40 
      --prefetch-multiplier=1"
    networks:
      - app-network
    depends_on:
      - dataBase
      - redis
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: dataBase
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      GLOBAL_WORK_MODE: 'imitation'
    volumes:
      - ./MLPipeline/src/config:/app/src/config
      - ./MLPipeline/src/output:/app/src/output
      - ./MLPipeline/src/logs:/app/src/logs
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1768M
    restart: unless-stopped
    profiles: ["dev"]

  redis:
    image: redis:7-alpine
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped
    profiles: ["dev"]

  dataBase:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 384M
    restart: unless-stopped
    profiles: ["dev"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    restart: unless-stopped
    profiles: ["dev"]

volumes:
  db-data:
    name: projectsigmatrading_db-data
    driver: local

networks:
  app-network:
    driver: bridge
