name: Check Project Structure

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  check-folders:
    name: Check exist directories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check directory frontend
        run: |
          if [ -d "frontend" ]; then
            echo "✅ Folder frontend is finded"
          else
            echo "❌ Folder frontend is not finded!"
            exit 1
          fi
      
      - name: Check directory backend
        run: |
          if [ -d "backend" ]; then
            echo "✅ Folder backend is finded"
          else
            echo "❌ Folder backend is not finded!"
            exit 1
          fi
      
      - name: Check directory MLPipeline
        run: |
          if [ -d "MLPipeline" ]; then
            echo "✅ Folder MLPipeline is finded"
          else
            echo "❌ Folder MLPipeline is not finded!"
            exit 1
          fi
      
      - name: All directories is finded!
        run: echo "🎉 Project's structure is correct!"